CMAKE_MINIMUM_REQUIRED(VERSION 3.25)
PROJECT(auto-create)

SET(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

INCLUDE_DIRECTORIES(include)
INCLUDE(cmake/SetupDateBasedOutput.cmake)


ADD_COMPILE_DEFINITIONS(_WIN32_WINNT=0x0601)

SET(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
SET(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /MT")
SET(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELEASE} /MT")
SET(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} /MTd")

ADD_EXECUTABLE(${PROJECT_NAME}
    dir_item.cpp
    dir_item.hpp
    main.cpp
    utils.cpp
    utils.hpp
)
INCLUDE(cmake/post-build.cmake)
TARGET_COMPILE_DEFINITIONS(${PROJECT_NAME} PRIVATE
    NOMINMAX            # 防止Windows.h定义min/max宏
    WIN32_LEAN_AND_MEAN # 减少Windows.h包含内容，提高编译速度
)
